---
- name: save config to nvram 
  connection: network_cli
  hosts: Routers
  tasks: 
    - name: save to nvram 
      ios_config: 
          save_when: always  
      register: output

    - name: display output
      debug:
        var: output
